// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA3680y15IQWs5-e4AVOQUXektRrcDUFk',
    appId: '1:313268404073:android:3c8bca8fc9bf4f7d4a47f8',
    messagingSenderId: '313268404073',
    projectId: 'ednect-modernhs',
    storageBucket: 'ednect-modernhs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnGwIMWTs1mdHkJOOJCIA3xgxPGNpE2fM',
    appId: '1:313268404073:ios:f27956314a59d2e84a47f8',
    messagingSenderId: '313268404073',
    projectId: 'ednect-modernhs',
    storageBucket: 'ednect-modernhs.firebasestorage.app',
    iosBundleId: 'com.ednect.modernhs',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJdhHqfjItE6dWI4qEzEOvGhs9N7OzCt4',
    appId: '1:519788502113:web:08deb48681443bb95a9e20',
    messagingSenderId: '519788502113',
    projectId: 'ednect-holychild-bijni',
    authDomain: 'ednect-holychild-bijni.firebaseapp.com',
    storageBucket: 'ednect-holychild-bijni.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoLUIDUtFGGfkqQSyYLRRHEU3IcB7OqtQ',
    appId: '1:519788502113:ios:0c939bc129d8e50e5a9e20',
    messagingSenderId: '519788502113',
    projectId: 'ednect-holychild-bijni',
    storageBucket: 'ednect-holychild-bijni.firebasestorage.app',
    iosBundleId: 'com.example.ednectHolichildBijni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJdhHqfjItE6dWI4qEzEOvGhs9N7OzCt4',
    appId: '1:519788502113:web:ac9982091558d2465a9e20',
    messagingSenderId: '519788502113',
    projectId: 'ednect-holychild-bijni',
    authDomain: 'ednect-holychild-bijni.firebaseapp.com',
    storageBucket: 'ednect-holychild-bijni.firebasestorage.app',
  );

}