// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA3680y15IQWs5-e4AVOQUXektRrcDUFk',
    appId: '1:313268404073:android:057df8a0d2b3540d4a47f8',
    messagingSenderId: '313268404073',
    projectId: 'ednect-modernhs',
    storageBucket: 'ednect-modernhs.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnGwIMWTs1mdHkJOOJCIA3xgxPGNpE2fM',
    appId: '1:313268404073:ios:e9bf2d92707966074a47f8',
    messagingSenderId: '313268404073',
    projectId: 'ednect-modernhs',
    storageBucket: 'ednect-modernhs.firebasestorage.app',
    iosBundleId: 'com.ednect.stjudeschool',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIIymcEF0GUHc-ILyOJp8ziS2OTCayMHg',
    appId: '1:313268404073:web:1cdc53e1e749f9d94a47f8',
    messagingSenderId: '313268404073',
    projectId: 'ednect-modernhs',
    authDomain: 'ednect-modernhs.firebaseapp.com',
    storageBucket: 'ednect-modernhs.firebasestorage.app',
    measurementId: 'G-XV6X5GLW04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnGwIMWTs1mdHkJOOJCIA3xgxPGNpE2fM',
    appId: '1:313268404073:ios:256c1e179b8ca0324a47f8',
    messagingSenderId: '313268404073',
    projectId: 'ednect-modernhs',
    storageBucket: 'ednect-modernhs.firebasestorage.app',
    iosBundleId: 'com.example.stJudeSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIIymcEF0GUHc-ILyOJp8ziS2OTCayMHg',
    appId: '1:313268404073:web:0b0e8f16b010bc704a47f8',
    messagingSenderId: '313268404073',
    projectId: 'ednect-modernhs',
    authDomain: 'ednect-modernhs.firebaseapp.com',
    storageBucket: 'ednect-modernhs.firebasestorage.app',
    measurementId: 'G-2X4K56L900',
  );
}
